config/routes.rb
Rails.application.routes.draw do
  resources :role_users
  get 'welcome/index', as: :index 
  get 'welcome/insufficient_privileges', as: :ip

  resources :roles
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role_user.rb
# Связь пользователя с ролью
# role - роль
# user - пользователь
# data - параметр связи (например, код факультета)

class RoleUser < ApplicationRecord
  belongs_to :role
  belongs_to :user
  
  validates :role_id, presence: true
  validates :user_id, presence: true
  
  Role::ROLE_FOR_METHODS.each do |rname|
    define_method "is_#{rname}?" do
      self.role.name == rname
    end
  end
end

app/controllers/role_users_controller.rb
class RoleUsersController < ApplicationController
  before_action :set_role_user, only: [:show, :edit, :update, :destroy]

  # GET /role_users
  # GET /role_users.json
  def index
    @role_users = RoleUser.all
  end

  # GET /role_users/1
  # GET /role_users/1.json
  def show
  end

  # GET /role_users/new
  def new
    @role_user = RoleUser.new
  end

  # GET /role_users/1/edit
  def edit
  end

  # POST /role_users
  # POST /role_users.json
  def create
    @role_user = RoleUser.new(role_user_params)

    respond_to do |format|
      if @role_user.save
        format.html { redirect_to @role_user, notice: 'Role user was successfully created.' }
        format.json { render :show, status: :created, location: @role_user }
      else
        format.html { render :new }
        format.json { render json: @role_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /role_users/1
  # PATCH/PUT /role_users/1.json
  def update
    respond_to do |format|
      if @role_user.update(role_user_params)
        format.html { redirect_to @role_user, notice: 'Role user was successfully updated.' }
        format.json { render :show, status: :ok, location: @role_user }
      else
        format.html { render :edit }
        format.json { render json: @role_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_users/1
  # DELETE /role_users/1.json
  def destroy
    @role_user.destroy
    respond_to do |format|
      format.html { redirect_to role_users_url, notice: 'Role user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role_user
      @role_user = RoleUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_user_params
      params.require(:role_user).permit(:role_id, :user_id, :data)
    end
end

app/helpers/role_users_helper.rb
module RoleUsersHelper
end

app/views/role_users/_form.html.haml
= form_for @role_user do |f|
  - if @role_user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@role_user.errors.count, "error")} prohibited this role_user from being saved:"
      %ul
        - @role_user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :role
    = f.text_field :role
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :data
    = f.text_field :data
  .actions
    = f.submit 'Save'

app/views/role_users/edit.html.haml
%h1 Editing role_user

= render 'form'

= link_to 'Show', @role_user
\|
= link_to 'Back', role_users_path

app/views/role_users/index.html.haml
%h1 Listing role_users

%table
  %thead
    %tr
      %th Role
      %th User
      %th Data
      %th
      %th
      %th

  %tbody
    - @role_users.each do |role_user|
      %tr
        %td= role_user.role
        %td= role_user.user
        %td= role_user.data
        %td= link_to 'Show', role_user
        %td= link_to 'Edit', edit_role_user_path(role_user)
        %td= link_to 'Destroy', role_user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Role user', new_role_user_path

app/views/role_users/new.html.haml
%h1 New role_user

= render 'form'

= link_to 'Back', role_users_path

app/views/role_users/show.html.haml
%p#notice= notice

%p
  %b Role:
  = @role_user.role
%p
  %b User:
  = @role_user.user
%p
  %b Data:
  = @role_user.data

= link_to 'Edit', edit_role_user_path(@role_user)
\|
= link_to 'Back', role_users_path