config/routes.rb
Rails.application.routes.draw do
  resources :role_users
  get 'welcome/index', as: :index 
  get 'welcome/insufficient_privileges', as: :ip

  resources :roles
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/role.rb
# Роль пользователя
# name - название роли (латиницей)
# info - сокращённое название (кириллицей)
# full_info - полное название (кириллицей)

class Role < ApplicationRecord
  has_many :role_users

  validates :name, presence: true, uniqueness: true   
  validates :info, presence: true, uniqueness: true
  validates :full_info, presence: true, uniqueness: true 
  
  def self.create_main_roles
    r1 = Role.find_or_create_by(name: 'admin', 
      info: 'Администратор',
      full_info: 'Администратор системы')
    r2 = Role.find_or_create_by(name: 'operator', 
      info: 'Оператор',
      full_info: 'Оператор')
    [r1, r2]
  end

  ROLE_FOR_METHODS = ['admin', 'operator']
  
  ROLE_FOR_METHODS.each do |rname|
    define_method "is_#{rname}?" do
      self.role_name_eng == rname
    end
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :info, :full_info)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.haml
= form_for @role do |f|
  - if @role.errors.any?
    #error_explanation
      %h2= "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"
      %ul
        - @role.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :info
    = f.text_field :info
  .field
    = f.label :full_info
    = f.text_area :full_info
  .actions
    = f.submit 'Save'

app/views/roles/edit.html.haml
%h1 Editing role

= render 'form'

= link_to 'Show', @role
\|
= link_to 'Back', roles_path

app/views/roles/index.html.haml
%h1 Listing roles

%table
  %thead
    %tr
      %th Name
      %th Info
      %th Full info
      %th
      %th
      %th

  %tbody
    - @roles.each do |role|
      %tr
        %td= role.name
        %td= role.info
        %td= role.full_info
        %td= link_to 'Show', role
        %td= link_to 'Edit', edit_role_path(role)
        %td= link_to 'Destroy', role, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Role', new_role_path

app/views/roles/new.html.haml
%h1 New role

= render 'form'

= link_to 'Back', roles_path

app/views/roles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @role.name
%p
  %b Info:
  = @role.info
%p
  %b Full info:
  = @role.full_info

= link_to 'Edit', edit_role_path(@role)
\|
= link_to 'Back', roles_path