config/routes.rb
Rails.application.routes.draw do
  resources :role_users
  get 'welcome/index', as: :index 
  get 'welcome/insufficient_privileges', as: :ip

  resources :roles
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  ## Эти методы надо показывать всем
  skip_before_action :check_app_auth
  
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to(root_path(), notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end    
  end

  def destroy
    logout
    redirect_to(login_path(), notice: 'Logged out!')    
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.haml
= form_tag user_sessions_path, :method => :post do
  .field
    = label_tag :email
    = text_field_tag :email
  .field
    = label_tag :password
    = password_field_tag :password
  .field
    = check_box_tag :remember, params[:remember], true
    = label_tag :remember
  .actions
    = submit_tag "Login"

app/views/user_sessions/new.html.haml
%h1
  Login

= render 'form'

= link_to 'Back', user_sessions_path